name: Generate Contributors List

on:
  push:
    branches:
      - script

jobs:
  generate-contributors-list-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the script
        run: ./generate-contributors-list.swift
